name: My Test Workflows
on:
  push:
    branches:
      - master 
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: My First Step
        run: echo Hello World
      - name: My Second Step
        run: |
          echo My First Echo
          echo My Second Echo