name: My Test Workflows
on:
  push:
    branches:
      - master 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'

    - name: Установка зависимостей
      run: npm install

    - name: Run tests
      run: npm test
  print:
    runs-on: ubuntu-latest
    steps:
      - name: My First Step
        run: echo Hello World
      - name: My Second Step
        run: |
          echo My First Echo
          echo My Second Echo
