name: My Test Workflows
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: My First Step
        run: echo Hello World
      - name: My Second Step
        run: |
          echo First Operation
          echo Second Operation